/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema.presentacion.pagos;

import java.util.Observable;
import sistema.logic.Prestamo;

/**
 *
 * @author 50663
 */
public class View extends javax.swing.JFrame implements java.util.Observer{

    /**
     * Creates new form View
     */
    Model model;
    Controller controller;
    
    public View() {
        initComponents();
    }

    public Model getModel() {
        return model;
    }

    public void setModel(Model model) {
        this.model = model;
        model.addObserver(this);
    }

    public Controller getController() {
        return controller;
    }

    public void setController(Controller controller) {
        this.controller = controller;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        detallesLbl = new javax.swing.JLabel();
        numeroLbl = new javax.swing.JLabel();
        numeroTxtField = new javax.swing.JTextField();
        descripcionLbl = new javax.swing.JLabel();
        descripcionTxtField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        mensualidadesTable = new javax.swing.JTable();
        metodosPagoLbl = new javax.swing.JLabel();
        plazoLbl = new javax.swing.JLabel();
        plazoTxtField = new javax.swing.JTextField();
        interesLbl = new javax.swing.JLabel();
        interesTxtField = new javax.swing.JTextField();
        regresarBtn = new javax.swing.JButton();
        metodoPagoComboBox = new javax.swing.JComboBox<>();
        montoTxtField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        procesarBtn = new javax.swing.JButton();
        realizarPagoLbl = new javax.swing.JLabel();
        cuotaLbl = new javax.swing.JLabel();
        cuotaTxtField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        montoPendienteTxtField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pago Prestamos");

        detallesLbl.setText("Detalles del Prestamo");

        numeroLbl.setText("Numero");

        numeroTxtField.setEditable(false);

        descripcionLbl.setText("Descripcion");

        descripcionTxtField.setEditable(false);

        mensualidadesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(mensualidadesTable);

        metodosPagoLbl.setText("Metodos de pago");

        plazoLbl.setText("Plazo");

        plazoTxtField.setEditable(false);

        interesLbl.setText("Interes");

        interesTxtField.setEditable(false);

        regresarBtn.setText("Regresar");
        regresarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarBtnActionPerformed(evt);
            }
        });

        metodoPagoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un metodo", "Pago Cuota", "Pago extraordinario" }));
        metodoPagoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metodoPagoComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Monto");

        procesarBtn.setText("Procesar");
        procesarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procesarBtnActionPerformed(evt);
            }
        });

        realizarPagoLbl.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        realizarPagoLbl.setText("Realizar pago");

        cuotaLbl.setText("Cuota");

        cuotaTxtField.setEditable(false);

        jLabel2.setText("Monto pendiente");

        montoPendienteTxtField.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(metodosPagoLbl))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(montoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(metodoPagoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(198, 198, 198))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(procesarBtn)
                        .addGap(160, 160, 160)
                        .addComponent(regresarBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(descripcionLbl)
                            .addComponent(numeroLbl)
                            .addComponent(plazoLbl)
                            .addComponent(interesLbl)
                            .addComponent(cuotaLbl)
                            .addComponent(jLabel2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(numeroTxtField, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                    .addComponent(descripcionTxtField)
                                    .addComponent(plazoTxtField)
                                    .addComponent(interesTxtField)
                                    .addComponent(cuotaTxtField)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(montoPendienteTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(detallesLbl))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(realizarPagoLbl)
                .addGap(242, 242, 242))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(detallesLbl)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(regresarBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(numeroTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numeroLbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(descripcionTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(descripcionLbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(plazoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(plazoLbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(interesTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(interesLbl))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cuotaLbl)
                                    .addComponent(cuotaTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(montoPendienteTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(realizarPagoLbl)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(metodosPagoLbl)
                                    .addComponent(metodoPagoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(montoTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(procesarBtn)
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarBtnActionPerformed
        controller.exit();
    }//GEN-LAST:event_regresarBtnActionPerformed

    private void metodoPagoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metodoPagoComboBoxActionPerformed
       
        String text= (String) metodoPagoComboBox.getSelectedItem();
        
        if(text.equals("Pago Cuota")){
            
            montoTxtField.setText(""+model.getPrestamo().cuotaMensual());
            montoTxtField.setEditable(false);
        }
        else{
             montoTxtField.setText("");
            montoTxtField.setEditable(true);
        }
    }//GEN-LAST:event_metodoPagoComboBoxActionPerformed

    private void procesarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procesarBtnActionPerformed
       
        String text= (String) metodoPagoComboBox.getSelectedItem();
        
        if(text.equals("Pago Cuota")){
        controller.pagoCuota(Double.parseDouble(montoTxtField.getText()));
        }
        else if(text.equals("Pago extraordinario")){
        controller.pagoCuotaExtraordinario(Double.parseDouble(montoTxtField.getText()));
        }
    }//GEN-LAST:event_procesarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cuotaLbl;
    private javax.swing.JTextField cuotaTxtField;
    private javax.swing.JLabel descripcionLbl;
    private javax.swing.JTextField descripcionTxtField;
    private javax.swing.JLabel detallesLbl;
    private javax.swing.JLabel interesLbl;
    private javax.swing.JTextField interesTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable mensualidadesTable;
    private javax.swing.JComboBox<String> metodoPagoComboBox;
    private javax.swing.JLabel metodosPagoLbl;
    private javax.swing.JTextField montoPendienteTxtField;
    private javax.swing.JTextField montoTxtField;
    private javax.swing.JLabel numeroLbl;
    private javax.swing.JTextField numeroTxtField;
    private javax.swing.JLabel plazoLbl;
    private javax.swing.JTextField plazoTxtField;
    private javax.swing.JButton procesarBtn;
    private javax.swing.JLabel realizarPagoLbl;
    private javax.swing.JButton regresarBtn;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
       
        Prestamo prestamo= model.getPrestamo();
        
        numeroTxtField.setText(""+prestamo.getNumber());
        descripcionTxtField.setText(prestamo.getDescripcion());
        plazoTxtField.setText(""+prestamo.getPlazo());
        interesTxtField.setText(""+prestamo.getTasaInteres());
        cuotaTxtField.setText(""+prestamo.cuotaMensual());
        
        if(!prestamo.getListaFacturas().isEmpty()){
        montoPendienteTxtField.setText(""+ (prestamo.getListaFacturas().get(prestamo.getListaFacturas().size()-1).
        getMensualidad().getSaldo() - prestamo.getListaFacturas().get((prestamo.getListaFacturas().size()-1)).getMensualidad()
        .getAmortizacion()));
        }
        else{
             montoPendienteTxtField.setText(""+prestamo.getMonto());
        }
        
        mensualidadesTable.setModel(new PagosTableModel(prestamo));
        
    }
}
